export const DIVISION = {
  REHABILITAS_SOSIAL: "RESOS",
  PERLINDUNGAN_JAMINAN_SOSIAL: "LINJAMSOS",
  PENANGANAN_SOSIAL_DAN_FAKIR_MISKIN: "PFM",
};

export const STATUS = {
  NOT_COMPLETED: "NOT COMPLETED",
  COMPLETED: "COMPLETED",
  CANCELED: "CANCELED",
};
